import "server-only";

// Overhaul drafts + signer invites: service-role writes. Same posture as
// attendance-mutations.ts — every function throws when Supabase isn't
// configured (a silently no-op write here would lose a wizard autosave or an
// invite acceptance), and reuses the singleton client from ./mutations rather
// than opening a second connection. Reads live in ./draft-queries.ts.
//
// 0005 enables RLS on both tables with zero anon policies, so the service
// client is the ONLY way in; every caller must have already established that
// the actor may touch this draft.

import { fail } from "@/lib/errors";
// The invite deadline is one rule with two enforcement points: derived when a
// seat is read, filtered when it is written. Both live next to the read
// boundary that owns it, so they can never drift apart.
import { inviteExpiryCutoff } from "./draft-queries";
import { dbConfigured, getServiceClient } from "./mutations";
import type {
  EditionDraftMeta,
  EditionDraftRow,
  SignerInviteRow,
} from "./types";

// ---------------------------------------------------------------------------
// drafts
// ---------------------------------------------------------------------------

export interface InsertDraftInput {
  meta: EditionDraftMeta;
  /** Privy DID of the creator — `edition_drafts.created_by`. */
  createdBy: string;
}

/** Opens an empty draft at wizard step 1; everything else fills in via updateDraft. */
export async function insertDraft(
  input: InsertDraftInput,
): Promise<EditionDraftRow> {
  if (!dbConfigured) fail("INTERNAL", "Supabase não configurado.");
  const supabase = getServiceClient();
  const { data, error } = await supabase
    .from("edition_drafts")
    .insert({ meta: input.meta, created_by: input.createdBy })
    .select()
    .single();
  if (error) {
    fail("INTERNAL", "Falha ao criar rascunho.", {
      detail: error.message,
      retryable: true,
    });
  }
  return data as EditionDraftRow;
}

export type DraftPatch = Partial<
  Pick<EditionDraftRow, "meta" | "layout" | "template_sha" | "chain_address">
>;

/**
 * Column-scoped patch: only the keys the caller passes are written, so the
 * wizard's per-step autosaves (metadata on step 1, layout on step 4) never
 * clobber each other. `updated_at` is maintained here — 0005 gives the column
 * a default but no trigger.
 */
export async function updateDraft(
  id: string,
  patch: DraftPatch,
): Promise<EditionDraftRow> {
  if (!dbConfigured) fail("INTERNAL", "Supabase não configurado.");
  const supabase = getServiceClient();
  const { data, error } = await supabase
    .from("edition_drafts")
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq("id", id)
    .select()
    .maybeSingle();
  if (error) {
    fail("INTERNAL", "Falha ao salvar rascunho.", {
      detail: error.message,
      retryable: true,
    });
  }
  if (!data) {
    fail("NOT_FOUND", "Rascunho não encontrado.");
  }
  return data as EditionDraftRow;
}

// ---------------------------------------------------------------------------
// signer invites
// ---------------------------------------------------------------------------

export interface InviteSeatInput {
  name: string;
  role: string;
  email: string;
  /** Bearer token for `/invite/[token]` — generated by the caller. */
  token: string;
  /**
   * Set only by the manual-wallet escape hatch, which skips the invite round
   * trip entirely: the seat is born accepted and its token is never sent
   * anywhere.
   */
  wallet?: string | null;
}

/**
 * Creates the draft's seats in one round-trip. Tokens are passed through
 * exactly as given: `signer_invites.token` is uniquely indexed, so a collision
 * surfaces as a failed insert here rather than being papered over — two seats
 * sharing a magic link would let one signer bind the other's seat.
 */
export async function insertInvites(
  draftId: string,
  seats: InviteSeatInput[],
): Promise<SignerInviteRow[]> {
  if (seats.length === 0) {
    return [];
  }
  if (!dbConfigured) fail("INTERNAL", "Supabase não configurado.");
  const supabase = getServiceClient();
  const now = new Date().toISOString();
  const { data, error } = await supabase
    .from("signer_invites")
    .insert(
      seats.map((seat) => ({
        draft_id: draftId,
        name: seat.name,
        role: seat.role,
        email: seat.email,
        token: seat.token,
        ...(seat.wallet
          ? { wallet: seat.wallet, status: "accepted", accepted_at: now }
          : {}),
      })),
    )
    .select();
  if (error) {
    fail("INTERNAL", "Falha ao registrar signatários.", {
      detail: error.message,
      retryable: true,
    });
  }
  return (data ?? []) as SignerInviteRow[];
}

/**
 * Binds a wallet to a seat, single-use. The `status = 'invited'` filter rides
 * along with the UPDATE so Postgres arbitrates: a second accept (a re-opened
 * magic link, two tabs, a forwarded email) matches zero rows and lands in the
 * CONFLICT branch instead of silently re-binding the seat to a different
 * wallet. The `invited_at` cutoff rides along for the same reason — the
 * 14-day deadline is derived on read (getInviteByToken), so without it here a
 * caller that skipped the read could still bind an aged-out seat. Callers that
 * need to distinguish "already accepted" from "expired" read the row first.
 */
export async function acceptInvite(
  id: string,
  wallet: string,
): Promise<SignerInviteRow> {
  if (!dbConfigured) fail("INTERNAL", "Supabase não configurado.");
  const supabase = getServiceClient();
  const { data, error } = await supabase
    .from("signer_invites")
    .update({
      status: "accepted",
      wallet,
      accepted_at: new Date().toISOString(),
    })
    .eq("id", id)
    .eq("status", "invited")
    .gt("invited_at", inviteExpiryCutoff())
    .select()
    .maybeSingle();
  if (error) {
    fail("INTERNAL", "Falha ao confirmar convite.", {
      detail: error.message,
      retryable: true,
    });
  }
  if (!data) {
    fail("CONFLICT", "Este convite já foi utilizado ou não está mais válido.");
  }
  return data as SignerInviteRow;
}

/**
 * Removes a seat from a draft. Scoped by `draft_id` as well as `id` so a
 * mistyped id can never delete another draft's seat.
 */
export async function deleteInvite(
  draftId: string,
  inviteId: string,
): Promise<void> {
  if (!dbConfigured) fail("INTERNAL", "Supabase não configurado.");
  const supabase = getServiceClient();
  const { error } = await supabase
    .from("signer_invites")
    .delete()
    .eq("id", inviteId)
    .eq("draft_id", draftId);
  if (error) {
    fail("INTERNAL", "Falha ao remover signatário.", {
      detail: error.message,
      retryable: true,
    });
  }
}

/** Stamps the last reminder time — display only; `notifyOnce` owns the rate limit. */
export async function touchInviteReminded(inviteId: string): Promise<void> {
  if (!dbConfigured) fail("INTERNAL", "Supabase não configurado.");
  const supabase = getServiceClient();
  const { error } = await supabase
    .from("signer_invites")
    .update({ reminded_at: new Date().toISOString() })
    .eq("id", inviteId);
  if (error) {
    fail("INTERNAL", "Falha ao registrar lembrete.", {
      detail: error.message,
      retryable: true,
    });
  }
}
